#!/usr/bin/env bash
set -euo pipefail

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

error() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

prompt() {
  local label="$1"
  local default_value="${2:-}"
  local input

  if [[ -n "$default_value" ]]; then
    read -r -p "$label [$default_value]: " input || true
    if [[ -z "${input:-}" ]]; then
      input="$default_value"
    fi
  else
    read -r -p "$label: " input || true
  fi

  printf '%s' "$input"
}

dotenv_line() {
  local key="$1"
  local value="$2"
  local escaped

  if [[ "$value" =~ [[:space:]#\"\'\\] ]]; then
    escaped="${value//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    printf '%s="%s"\n' "$key" "$escaped"
  else
    printf '%s=%s\n' "$key" "$value"
  fi
}

run_privileged() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  elif command -v sudo >/dev/null 2>&1; then
    sudo "$@"
  else
    error "Privilege escalation required for: $* (install sudo or run as root)"
  fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$SCRIPT_DIR"

if [[ ! -f "$PROJECT_DIR/docker-compose.yml" ]]; then
  REPO_URL="$(prompt "Git repo URL for onlydropbox" "https://github.com/adclab/onlydropbox.git")"
  PROJECT_DIR="$(prompt "Install directory" "/opt/onlydropbox")"

  if [[ -d "$PROJECT_DIR/.git" ]]; then
    log "Existing git repo found at $PROJECT_DIR. Pulling latest changes."
    git -C "$PROJECT_DIR" pull --ff-only
  elif [[ -d "$PROJECT_DIR" && -n "$(ls -A "$PROJECT_DIR" 2>/dev/null || true)" ]]; then
    error "Install directory is not empty: $PROJECT_DIR"
  else
    log "Cloning $REPO_URL into $PROJECT_DIR"
    run_privileged mkdir -p "$PROJECT_DIR"
    run_privileged chown "$(id -u):$(id -g)" "$PROJECT_DIR"
    git clone "$REPO_URL" "$PROJECT_DIR"
  fi
fi

[[ -f "$PROJECT_DIR/docker-compose.yml" ]] || error "docker-compose.yml not found in $PROJECT_DIR"

if ! command -v git >/dev/null 2>&1 || ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
  log "Installing Docker Engine and Docker Compose plugin (Debian/Ubuntu apt packages)."
  command -v apt-get >/dev/null 2>&1 || error "apt-get not found. Install Docker manually, then re-run."
  run_privileged apt-get update
  run_privileged env DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl git docker.io docker-compose-plugin
fi

if command -v systemctl >/dev/null 2>&1; then
  run_privileged systemctl enable --now docker >/dev/null 2>&1 || true
fi

DOCKER_RUN=()
if docker info >/dev/null 2>&1; then
  DOCKER_RUN=(docker)
else
  if [[ "${EUID}" -eq 0 ]]; then
    DOCKER_RUN=(docker)
  elif command -v sudo >/dev/null 2>&1; then
    DOCKER_RUN=(sudo docker)
  else
    error "Docker daemon is not accessible. Run as root, enable Docker for this user, or install sudo."
  fi
fi

PREFIX_PATH="$(prompt "PREFIX_PATH (Dropbox base path)" "/")"
SYNC_FOLDERS="$(prompt "SYNC_FOLDERS (comma-separated first-level folders to sync; empty = unchanged)" "")"

mkdir -p "$PROJECT_DIR/data/dropbox-config" "$PROJECT_DIR/data/dropbox-sync"

{
  printf '# Generated by install-onlydropbox-lxc.sh on %s\n' "$(date '+%Y-%m-%d %H:%M:%S')"
  printf '# Base Dropbox path where selective sync rules are applied.\n'
  dotenv_line "PREFIX_PATH" "$PREFIX_PATH"
  printf '\n# Comma-separated folder names to sync within PREFIX_PATH.\n'
  dotenv_line "SYNC_FOLDERS" "$SYNC_FOLDERS"
} > "$PROJECT_DIR/.env"

log "Wrote env config to $PROJECT_DIR/.env"
log "Starting onlydropbox via Docker Compose..."
(
  cd "$PROJECT_DIR"
  "${DOCKER_RUN[@]}" compose up -d --build
)

cat <<EOF

Install complete.

Next steps:
1. Link Dropbox account (first run only):
   ${DOCKER_RUN[*]} logs -f onlydropbox
   Open the Dropbox URL printed in the logs.
2. Restart once after linking:
   (cd "$PROJECT_DIR" && ${DOCKER_RUN[*]} compose restart)

Configured values:
  PREFIX_PATH=$PREFIX_PATH
  SYNC_FOLDERS=$SYNC_FOLDERS

EOF
